apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sample.crd.example.com
spec:
  group: crd.example.com
  version: v1
  scope: Namespaced
  names:
    plural: samples
    singular: sample
    kind: Sample
    shortNames: ["smpl"]
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: sample-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: crd.example.com/v1
    resource: sample
  #childResources:
  #  - apiVersion: v1
  #    resource: pods
  hooks:
    sync:
      webhook:
        url: http://sample-controller.metacontroller/
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-controller
  template:
    metadata:
      labels:
        app: sample-controller
    spec:
      containers:
      - name: controller
        image: ctracey/kube-controller
        command: ["kube-controller", "meta"]
        volumeMounts:
        - name: hooks
          mountPath: /hooks
      volumes:
      - name: hooks
        configMap:
          name: indexedjob-controller
---
apiVersion: v1
kind: Service
metadata:
  name: sample-controller
  namespace: metacontroller
spec:
  selector:
    app: sample-controller
  ports:
  - port: 8080
