---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: samples-reader
rules:
- apiGroups: ["crd.example.com"]
  resources: ["samples"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-sampless-global
subjects:
- kind: User
  name: system:serviceaccount:metacontroller:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: samples-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sample-controller-native
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-controller-native
  template:
    metadata:
      labels:
        app: sample-controller-native
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-10-0-26-37.ec2.internal
      containers:
      - name: controller
        image: ctracey/kube-controller
        command: ["kube-controller", "native"]
        imagePullPolicy: Never
